server.port: 8081
spring:
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      enable-auto-commit: false
      group-id: loc-kafka-sample
    listener:
      ack-mode: record
