version: "3"

services:
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    restart: always
    container_name: keycloak
    environment:
        - 'DB_VENDOR=MYSQL'
        - 'MYSQL_PORT_3306_TCP_ADDR=mysql'
        - 'MYSQL_PORT_3306_TCP_PORT=3306'
        - 'MYSQL_DATABASE=loc_db'             #mysql数据库
        - 'MYSQL_USER=root'                   #mysql用户名
        - 'MYSQL_PASSWORD=password'           #mysql密码
        - 'KEYCLOAK_USER=loc'                 #keycloak用户名
        - 'KEYCLOAK_PASSWORD=loc_password'    #keycloak密码
        - 'TZ=Asia/Shanghai'
    ports:
        - "7777:8080"
    depends_on:
        - mysql
  mysql:
    image: mysql:5.7.21
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /tmp/data/mysql:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=loc_db'
      - 'MYSQL_ROOT_PASSWORD=password'