server.port: 8081

spring.redis:
  host: 127.0.0.1
  port: 6379
#  cluster.nodes:
#    - 10.10.3.51:2001
#    - 10.10.3.51:2002
#    - 10.10.3.51:2003
  lettuce:
    pool:
      max-active: 10
      max-idle: 10
      max-wait: "1000"

